### ISSUE TITLE
SpacialEco requierment 

### ISSUE THREAD

**Issue by benlopez15** [OpenDroneMap/FIELDimageR#50]
Is there a fix for the SpatialEco requirement yet? 

ERROR: dependency 'spatialEco' is not available for package 'FIELDimageR'

**Comment by nfahlgren** [comment]
I believe the fix will not be easy and is related to #44. The R geospatial ecosystem is moving to a completely new set of packages. The `SpatialEco` package updated to use `sf` and the function used by FIELDimageR, `polyPerimeter`, now requires an `sf` polygon as input. So to use the newer versions of `SpatialEco` would require updating FIELDimageR to use `sf` instead of `sp` and related tools.

But it should probably be possible to specify that the version of `SpatialEco` must be < 2.

**Comment by nfahlgren** [comment]
I added a constraint to SpatialEco in #51 that you could try

**Comment by filipematias23** [comment]
Hi everyone, we are working on updating FIELDimageR and for now we are removing polyPerimeter and spacialEco from the package... Installation seems working ok now... Thanks for understanding.

**Comment by ArtKata** [comment]
Is there a way to use the previous version somehow? or R just won't let us?

**Comment by filipematias23** [comment]
Hi everyone,

Could you try installing it again?

*devtools::install_github("OpenDroneMap/FIELDimageR")*


Let us know if it works..!

All the best,
Filipe

Em qui., 26 de out. de 2023 às 05:34, Artūrs Katamadze <
***@***.***> escreveu:
